### ISSUE TITLE
Angular Universal - localstorage is undefined

### ISSUE THREAD

**Issue by TryHardDood** [ngneat/cashew#39]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using it with Angular Universal the localStorage is undefined.

## Environment

<pre><code>Angular version: 12.0.4</code></pre>

**Comment by NetanelBasal** [comment]
Can you share the code and when you get the error, please?

**Comment by TryHardDood** [comment]
Hi!
Sure.

Code: https://github.com/TryHardDood/ng-webcontainer-dcxape

Error:
```
ERROR ReferenceError: localStorage is not defined
    at Object.getItem (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:83762:23)
    at Map.get (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:83875:31)
    at HttpCacheInterceptor.intercept (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:83662:45)
    at HttpInterceptorHandler.handle (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:13187:33)
    at HttpXsrfInterceptor.intercept (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:13805:25)
    at HttpInterceptorHandler.handle (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:13187:33)
    at HttpInterceptingHandler.handle (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:13855:27)
    at ZoneClientBackend.delegate (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:82608:29)
    at scheduleTask (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:82535:39)
    at Observable._subscribe (C:\Projects\Home\ng-webcontainer-dcxape\dist\example-app\server\main.js:82574:13)
```

**Comment by NetanelBasal** [comment]
Which command did you run? I can't reproduce

**Comment by TryHardDood** [comment]
npm run dev:ssr

**Comment by NetanelBasal** [comment]
<img width="832" alt="Screen Shot 2021-06-16 at 14 28 14" src="https://user-images.githubusercontent.com/6745730/122211157-17dead00-ceaf-11eb-9db4-8818abfabdac.png">

**Comment by TryHardDood** [comment]
SSR does not work on stackblitz.

**Comment by NetanelBasal** [comment]
Oh ok

**Comment by NetanelBasal** [comment]
Try 2.0.3

**Comment by TryHardDood** [comment]
Thanks, it's working perfectly
